#!/usr/bin/with-contenv bash

source /etc/lsb-release

cat > /etc/apt/sources.list <<EOF
deb http://mirrors.ustc.edu.cn/ubuntu/ ${DISTRIB_CODENAME} main restricted universe multiverse
deb-src http://mirrors.ustc.edu.cn/ubuntu/ ${DISTRIB_CODENAME} main restricted universe multiverse

deb http://mirrors.ustc.edu.cn/ubuntu/ ${DISTRIB_CODENAME}-security main restricted universe multiverse
deb-src http://mirrors.ustc.edu.cn/ubuntu/ ${DISTRIB_CODENAME}-security main restricted universe multiverse

deb http://mirrors.ustc.edu.cn/ubuntu/ ${DISTRIB_CODENAME}-updates main restricted universe multiverse
deb-src http://mirrors.ustc.edu.cn/ubuntu/ ${DISTRIB_CODENAME}-updates main restricted universe multiverse

deb http://mirrors.ustc.edu.cn/ubuntu/ ${DISTRIB_CODENAME}-backports main restricted universe multiverse
deb-src http://mirrors.ustc.edu.cn/ubuntu/ ${DISTRIB_CODENAME}-backports main restricted universe multiverse
EOF

apt-get clean
apt-get update || apt-get update